Repository kuzzleio/documentation, pull requests merged in 2018-10, with the labels that each got.

#529 Update admin controller with refresh option and the lock
  src/api-documentation/controller-admin/dump.md
  src/api-documentation/controller-admin/reset-database.md
  src/api-documentation/controller-admin/reset-kuzzle-data.md
  src/api-documentation/controller-admin/reset-security.md
  src/api-documentation/controller-admin/shutdown.md
Labels: changelog:enhancements

#538 Fix script name in local strategy example with SDK
  src/guide/essentials/user-authentication.md
Labels: changelog:bug-fixes

#542 Release 1.4.1
  package-lock.json
  package.json
  src/api-documentation/controller-admin/dump.md
  src/api-documentation/controller-admin/reset-database.md
  src/api-documentation/controller-admin/reset-kuzzle-data.md
  src/api-documentation/controller-admin/reset-security.md
  src/api-documentation/controller-admin/shutdown.md
Labels: release

#540 Delete by query return
  src/api-documentation/controller-document/delete-by-query.md
Labels: changelog:bug-fixes

#545 Fix bulk return
  src/api-documentation/controller-bulk/import.md
Labels: changelog:bug-fixes

#547 Deprecate 3 realtime methods
  src/api-documentation/controller-realtime/list.md
  src/api-documentation/controller-realtime/validate.md
Labels: changelog:enhancements

#546 Fix realtime publish return
  src/api-documentation/controller-realtime/publish.md
Labels: changelog:bug-fixes
