Repository kuzzleio/documentation, pull requests merged in 2018-07, with the labels that each got.

#8 KZL-278 Bulk controller for SDK reference
  .prettierrc
  README.md
  package-lock.json
  package.json
  run_test.sh
  scaffold-example.js
  src/sdk-reference/bulk/code-example/import.cpp
  src/sdk-reference/bulk/code-example/import.go
  src/sdk-reference/bulk/code-example/import.java
  src/sdk-reference/bulk/code-example/import.js
  src/sdk-reference/bulk/code-example/import.yml
  src/sdk-reference/bulk/import.md
  src/sdk-reference/bulk/index.md
  src/sdk-reference/bulk/sections/importOptions_default.md
  src/sdk-reference/bulk/sections/importOptions_js.md
  src/sdk-reference/bulk/sections/importResponse_default.md
  src/sdk-reference/bulk/sections/importResponse_js.md
  src/sdk-reference/index/create.md
  src/sdk-reference/index/delete.md
  src/sdk-reference/index/get-auto-refresh.md
  src/sdk-reference/index/list.md
  src/sdk-reference/index/m-delete.md
  src/sdk-reference/index/refresh-internal.md
  src/sdk-reference/index/sections/createResponse_default.md
  src/sdk-reference/index/sections/deleteResponse_default.md
  src/sdk-reference/index/sections/refreshResponse_default.md
  src/sdk-reference/index/sections/setAutoRefreshResponse_default.md
  src/sdk-reference/index/set-auto-refresh.md
  test/templates/default.tpl.js
Labels: changelog:new-features

#13 Run one test
  .travis/stop_kuzzle.sh
  README.md
  docker/entrypoints/go.sh
  docker/entrypoints/js.sh
  docker/js
  package-lock.json
  run_test.sh
  test/lib/testManager.js
  test/main.js
  test/package-lock.json
Labels: changelog:enhancements

#16 Add eslint
  .eslintrc.json
  .travis.yml
  package-lock.json
  package.json
  run-all-snippets-tests.sh
  test/lib/helpers/file.js
  test/lib/helpers/logger.js
  test/lib/helpers/reports.js
  test/lib/testManager.js
  test/lib/testers/cppTester.js
  test/lib/testers/goTester.js
  test/lib/testers/javaTester.js
  test/lib/testers/jsTester.js
  test/lib/testers/tester.js
  test/main.js
Labels: changelog:exclude

#19 Change template + fix scaffodling
  plugins/sectionManager.js
  plugins/snippetManager.js
  scaffolding/lib/common.js
  scaffolding/templates/action.cpp.md
  scaffolding/templates/action.go.md
  scaffolding/templates/action.java.md
  scaffolding/templates/action.js.md
Labels: changelog:enhancements

#17 Refactor Bulk documentation
  index.js
  package-lock.json
  package.json
  src/assets/images/logos/cpp.png
  src/assets/images/logos/cpp.svg
  src/assets/images/logos/go.png
  src/assets/images/logos/go.svg
  src/assets/images/logos/java.png
  src/assets/images/logos/java.svg
  src/assets/images/logos/javascript.png
  src/assets/images/logos/javascript.svg
  src/assets/js/languageSelector.js
  src/assets/stylesheets/base/_typeset.scss
  src/assets/stylesheets/extensions/_select2.scss
  src/sdk-reference/bulk/import/import.cpp.md
  src/sdk-reference/bulk/import/import.go.md
  src/sdk-reference/bulk/import/import.java.md
  src/sdk-reference/bulk/import/import.js.md
  src/sdk-reference/bulk/import/index.md
  src/sdk-reference/bulk/import/sections/importOptions_default.md
  src/sdk-reference/bulk/import/sections/importOptions_js.md
  src/sdk-reference/bulk/import/sections/importResponse_default.md
  src/sdk-reference/bulk/import/sections/importResponse_js.md
  src/sdk-reference/index/create/index.md
Labels: changelog:exclude

#20 Add resolve and reject to js template
  scaffolding/templates/action.go.md
  scaffolding/templates/action.js.md
  scaffolding/templates/index.md
  scaffolding/templates/usage-snippets/usage.java
Labels: changelog:enhancements
