Repository kuzzleio/documentation, pull requests merged in 2018-08, with the labels that each got.

#508 Fix obsolete SDK "collection:create" documentation
  src/api-documentation/controller-collection/create.md
  src/sdk-reference/collection/create.md
Labels: changelog:enhancements

#511 auth:login responds with additional information
  src/api-documentation/controller-auth/login.md
  src/guide/essentials/user-authentication.md
  src/guide/kuzzle-depth/authentication.md
Labels: changelog:enhancements

#515 Apply eslint to plugins methods
  .eslintrc.json
  .travis.yml
  metalsmith-plugins/clickable-images.js
  metalsmith-plugins/language-tab.js
  metalsmith-plugins/logger.js
  metalsmith-plugins/metatoc.js
  metalsmith-plugins/save-src.js
  package-lock.json
  package.json
Labels: changelog:exclude

#518 Fix language tabs
  metalsmith-plugins/language-tab.js
Labels: changelog:bug-fixes

#519 Fix 423: better plugins prerequisites documentation
  package-lock.json
  src/404.md
  src/api-documentation/index.md
  src/assets/stylesheets/block-children/screen.scss
  src/assets/stylesheets/category-children/screen.scss
  src/elasticsearch-cookbook/index.md
  src/guide/code-examples/index.md
  src/guide/index.md
  src/index.md
  src/kuzzle-dsl/index.md
  src/kuzzle-events/index.md
  src/layouts/block-children.html.hbs
  src/layouts/category-children.html.hbs
  src/plugins-reference/index.md
  src/plugins-reference/plugins-creation-prerequisites/custom-plugin-configuration.md
  src/plugins-reference/plugins-creation-prerequisites/index.md
  src/plugins-reference/plugins-creation-prerequisites/plugin-init-function.md
  src/sdk-reference/index.md
  src/validation-reference/index.md
Labels: changelog:enhancements

#517 Document possible errors for Index and Collection controllers
  src/api-documentation/controller-collection/create.md
  src/api-documentation/controller-collection/delete-specifications.md
  src/api-documentation/controller-collection/exists.md
  src/api-documentation/controller-collection/get-mapping.md
  src/api-documentation/controller-collection/get-specifications.md
  src/api-documentation/controller-collection/list.md
  src/api-documentation/controller-collection/scroll-specifications.md
  src/api-documentation/controller-collection/search-specifications.md
  src/api-documentation/controller-collection/truncate.md
  src/api-documentation/controller-collection/update-mapping.md
  src/api-documentation/controller-collection/update-specifications.md
  src/api-documentation/controller-collection/validate-specifications.md
  src/api-documentation/controller-index/create.md
  src/api-documentation/controller-index/delete.md
  src/api-documentation/controller-index/exists.md
  src/api-documentation/controller-index/get-auto-refresh.md
  src/api-documentation/controller-index/list.md
  src/api-documentation/controller-index/m-delete.md
  src/api-documentation/controller-index/refresh-interval.md
  src/api-documentation/controller-index/refresh.md
  src/api-documentation/controller-index/set-auto-refresh.md
  src/api-documentation/errors/index.md
Labels: changelog:enhancements

#523 KZL 46 - Add metadata to published documents
  src/api-documentation/controller-realtime/publish.md
Labels: changelog:enhancements

#522 KZL 454 - Deprecate pending notifications
  src/api-documentation/notifications/document-creating.md
  src/api-documentation/notifications/document-deleting.md
  src/api-documentation/notifications/index.md
  src/sdk-reference/essentials/notifications.md
Labels: changelog:enhancements

#514 Harmonize scrollId parameter name
  src/api-documentation/controller-document/scroll.md
  src/api-documentation/controller-document/search.md
Labels: changelog:enhancements

#524 Prevent indexing to Algolia on every Travis Build
  .travis.yml
Labels: changelog:exclude

#521 KZL 290 - Add fixtures for securities in CLI
  src/guide/essentials/cli.md
Labels: changelog:new-features
