Repository kuzzleio/documentation, pull requests merged in 2018-09, with the labels that each got.

#525 Add Vfinder to the CI system
  .travis.yml
  .vfinder_exceptions
Labels: changelog:enhancements

#527 Add vfinder report with kuttlefish
  .travis.yml
  .vfinder/exceptions
  .vfinder/template.md
Labels: changelog:enhancements

#528 Release 1.3.0
  .travis.yml
  package-lock.json
  package.json
  src/404.md
  src/api-documentation/controller-auth/login.md
  src/api-documentation/controller-collection/create.md
  src/api-documentation/controller-collection/delete-specifications.md
  src/api-documentation/controller-collection/exists.md
  src/api-documentation/controller-collection/get-mapping.md
  src/api-documentation/controller-collection/get-specifications.md
  src/api-documentation/controller-collection/list.md
  src/api-documentation/controller-collection/scroll-specifications.md
  src/api-documentation/controller-collection/search-specifications.md
  src/api-documentation/controller-collection/truncate.md
  src/api-documentation/controller-collection/update-mapping.md
  src/api-documentation/controller-collection/update-specifications.md
  src/api-documentation/controller-collection/validate-specifications.md
  src/api-documentation/controller-document/scroll.md
  src/api-documentation/controller-document/search.md
  src/api-documentation/controller-index/create.md
  src/api-documentation/controller-index/delete.md
  src/api-documentation/controller-index/exists.md
  src/api-documentation/controller-index/get-auto-refresh.md
  src/api-documentation/controller-index/list.md
  src/api-documentation/controller-index/m-delete.md
  src/api-documentation/controller-index/refresh-interval.md
  src/api-documentation/controller-index/refresh.md
  src/api-documentation/controller-index/set-auto-refresh.md
  src/api-documentation/controller-realtime/publish.md
  src/api-documentation/errors/index.md
  src/api-documentation/index.md
  src/api-documentation/notifications/document-creating.md
  src/api-documentation/notifications/document-deleting.md
  src/api-documentation/notifications/index.md
  src/assets/stylesheets/block-children/screen.scss
  src/assets/stylesheets/category-children/screen.scss
  src/elasticsearch-cookbook/index.md
  src/guide/code-examples/index.md
  src/guide/essentials/cli.md
  src/guide/essentials/user-authentication.md
  src/guide/index.md
  src/guide/kuzzle-depth/authentication.md
  src/index.md
  src/kuzzle-dsl/index.md
  src/kuzzle-events/index.md
  src/layouts/block-children.html.hbs
  src/layouts/category-children.html.hbs
  src/plugins-reference/index.md
  src/plugins-reference/plugins-creation-prerequisites/custom-plugin-configuration.md
  src/plugins-reference/plugins-creation-prerequisites/index.md
  src/plugins-reference/plugins-creation-prerequisites/plugin-init-function.md
  src/sdk-reference/essentials/notifications.md
  src/sdk-reference/index.md
  src/validation-reference/index.md
Labels: release

#526 remove css & js packer
  index.js
  package-lock.json
  package.json
  src/assets/javascript/algolia-instant-search.js
  src/assets/libs/analytics.js
  src/assets/libs/jquery.barrating.js
  src/assets/libs/jquery.something.js
  src/assets/libs/turbolinks.js
  src/assets/libs/utils.js
  src/partials/common-meta.html
  src/partials/footer-scripts.html
Labels: changelog:bug-fixes

#530 Add hubspot chat script
  src/assets/javascript/analytics.js
  src/assets/javascript/turbolinks.js
  src/layouts/full.html.hbs
  src/partials/common-meta.html
  src/partials/footer-scripts.html
  src/partials/side-code.html
Labels: changelog:new-features

#532 Koncorde: new array value syntax documentation
  src/kuzzle-dsl/essential/arrayvalues.md
  src/kuzzle-dsl/essential/geodistances.md
  src/kuzzle-dsl/essential/nested.md
  src/kuzzle-dsl/terms/equals.md
  src/kuzzle-dsl/terms/exists.md
  src/kuzzle-dsl/terms/geo-bounding-box.md
  src/kuzzle-dsl/terms/geo-distance-range.md
  src/kuzzle-dsl/terms/geo-distance.md
  src/kuzzle-dsl/terms/geo-polygon.md
  src/kuzzle-dsl/terms/ids.md
  src/kuzzle-dsl/terms/in.md
  src/kuzzle-dsl/terms/missing.md
  src/kuzzle-dsl/terms/range.md
  src/kuzzle-dsl/terms/regexp.md
Labels: changelog:new-features

#533 Release 1.4.0
  index.js
  package-lock.json
  package.json
  src/api-documentation/controller-collection/create.md
  src/assets/javascript/algolia-instant-search.js
  src/assets/libs/analytics.js
  src/assets/libs/jquery.barrating.js
  src/assets/libs/jquery.something.js
  src/assets/libs/utils.js
  src/kuzzle-dsl/essential/arrayvalues.md
  src/kuzzle-dsl/essential/geodistances.md
  src/kuzzle-dsl/essential/nested.md
  src/kuzzle-dsl/terms/equals.md
  src/kuzzle-dsl/terms/exists.md
  src/kuzzle-dsl/terms/geo-bounding-box.md
  src/kuzzle-dsl/terms/geo-distance-range.md
  src/kuzzle-dsl/terms/geo-distance.md
  src/kuzzle-dsl/terms/geo-polygon.md
  src/kuzzle-dsl/terms/ids.md
  src/kuzzle-dsl/terms/in.md
  src/kuzzle-dsl/terms/missing.md
  src/kuzzle-dsl/terms/range.md
  src/kuzzle-dsl/terms/regexp.md
  src/partials/common-meta.html
  src/partials/footer-scripts.html
  src/sdk-reference/collection/create.md
Labels: release
