Repository kuzzleio/documentation, pull requests merged in 2018-10, with the labels that each got.

#48 use GOPATH for go signatures
  scaffolding/lib/utils.js
Labels: changelog:enhancements

#41 Add the possibility to exclude directories from the build
  README.md
  config/metalsmith.json
  config/versions.json
  getConfig.js
  helpers/handlebars.js
  index.js
  metalsmithOptions.js
  package.json
  plugins/anchors.js
  src/templates/partials/head.html
  src/templates/partials/header.html
  src/templates/partials/nav.html
  src/templates/partials/nav_sdk.html
Labels: changelog:new-features

#44 #KZL-498 Add version selector
  src/assets/images/logos/js.svg
  src/assets/js/.eslintrc.json
  src/assets/js/languageSelector.js
  src/assets/js/versionSelector.js
  src/assets/stylesheets/_config.scss
  src/assets/stylesheets/extensions/_select2.scss
  src/assets/stylesheets/layout/_nav.scss
  src/assets/stylesheets/layout/_sidebar.scss
  src/templates/full.html.hbs
  src/templates/partials/navMobile.html
  src/templates/sdk.html.hbs
Labels: changelog:enhancements

#43 KZL 516 - Update validateSpecifications return
  .ci/comment_pr.sh
  .ci/start_kuzzle.sh
  .ci/stop_kuzzle.sh
  src/sdk-reference/cpp/1/collection/validate-specifications/index.md
  src/sdk-reference/cpp/1/collection/validate-specifications/snippets/validate-specifications.cpp
  src/sdk-reference/go/1/collection/validate-specifications/index.md
  src/sdk-reference/go/1/collection/validate-specifications/snippets/validate-specifications.go
  src/sdk-reference/java/1/collection/validate-specifications/index.md
  src/sdk-reference/java/1/collection/validate-specifications/snippets/validate-specifications.java
  src/sdk-reference/js/6/collection/validate-specifications/index.md
  test/lib/testManager.js
  test/sdk-versions.yml
Labels: changelog:enhancements

#60 Fix left nav on sdk pages when section has no parent
  src/assets/stylesheets/_config.scss
  src/assets/stylesheets/layout/_nav.scss
  src/assets/stylesheets/libs/prism.css
  src/templates/partials/navMobile.html
  src/templates/partials/nav_sdk.html
Labels: changelog:bug-fixes

#51 KZL - 547 - Update validateSpecifications signature to take index and collection
  src/sdk-reference/cpp/1/collection/update-specifications/index.md
  src/sdk-reference/cpp/1/collection/update-specifications/snippets/update-specifications.cpp
  src/sdk-reference/cpp/1/collection/validate-specifications/index.md
  src/sdk-reference/cpp/1/collection/validate-specifications/snippets/validate-specifications.cpp
  src/sdk-reference/go/1/collection/update-specifications/index.md
  src/sdk-reference/go/1/collection/update-specifications/snippets/update-specifications.go
  src/sdk-reference/go/1/collection/validate-specifications/index.md
  src/sdk-reference/java/1/collection/update-specifications/index.md
  src/sdk-reference/java/1/collection/update-specifications/snippets/update-specifications.java
  src/sdk-reference/java/1/collection/validate-specifications/index.md
  src/sdk-reference/java/1/collection/validate-specifications/snippets/validate-specifications.java
  src/sdk-reference/js/6/collection/update-specifications/index.md
  src/sdk-reference/js/6/collection/update-specifications/snippets/update-specifications.js
  src/sdk-reference/js/6/collection/validate-specifications/index.md
  src/sdk-reference/js/6/collection/validate-specifications/snippets/validate-specifications.js
Labels: changelog:enhancements

#70 Change inline-blockquotes style to a more lighter one
  src/assets/stylesheets/_config.scss
  src/assets/stylesheets/base/_typeset.scss
Labels: changelog:enhancements

#75 [CSS] Fix noSidebar rule on tablet
  src/assets/stylesheets/layout/_sidebar.scss
Labels: changelog:bug-fixes

#72 KZL - 370 - Add error handling section
  src/sdk-reference/cpp/1/essentials/error-handling/index.md
  src/sdk-reference/cpp/1/essentials/error-handling/snippets/error-handling.cpp
  src/sdk-reference/cpp/1/essentials/error-handling/snippets/error-handling.test.yml
  src/sdk-reference/cpp/1/essentials/index.md
  src/sdk-reference/go/1/essentials/error-handling/index.md
  src/sdk-reference/go/1/essentials/error-handling/snippets/error-handling.go
  src/sdk-reference/go/1/essentials/error-handling/snippets/error-handling.test.yml
  src/sdk-reference/go/1/essentials/index.md
  src/sdk-reference/java/1/essentials/error-handling/index.md
  src/sdk-reference/java/1/essentials/error-handling/snippets/error-handling.java
  src/sdk-reference/java/1/essentials/error-handling/snippets/error-handling.test.yml
  src/sdk-reference/java/1/essentials/index.md
  src/sdk-reference/js/6/essentials/error-handling/index.md
  src/sdk-reference/js/6/essentials/error-handling/snippets/error-handling-async.js
  src/sdk-reference/js/6/essentials/error-handling/snippets/error-handling-async.test.yml
  src/sdk-reference/js/6/essentials/error-handling/snippets/error-handling.js
  src/sdk-reference/js/6/essentials/error-handling/snippets/error-handling.test.yml
  src/sdk-reference/js/6/essentials/index.md
Labels: changelog:new-features

#80 Add sdk beta languages
  src/assets/images/logos/android.svg
  src/assets/images/logos/csharp.svg
  src/assets/images/logos/go.svg
  src/assets/images/logos/lua.svg
  src/assets/images/logos/php.svg
  src/assets/images/logos/python.svg
  src/assets/images/logos/ruby.svg
  src/assets/stylesheets/extensions/_ribbon.scss
  src/assets/stylesheets/main.scss
  src/sdk-reference/index.md
Labels: changelog:enhancements

#88 Fix bulk return
  src/api/1/controller-bulk/import/index.md
Labels: changelog:bug-fixes

#96 KZL-738 Set middle content column margin to fit 80 chars in code blocks
  src/assets/stylesheets/layout/_content.scss
  src/assets/stylesheets/layout/_search.scss
  src/assets/stylesheets/layout/_sidebar.scss
Labels: changelog:enhancements

#97 [KZL-751] Add 404 page
  src/404.md
Labels: changelog:enhancements

#99 [fix] Fix kuzzle/addListener snippet and doc
  src/sdk-reference/go/1/kuzzle/add-listener/index.md
  src/sdk-reference/go/1/kuzzle/add-listener/snippets/add-listener.go
Labels: changelog:bug-fixes

#98 KZL-753 Disable hidden menu on scroll
  src/assets/js/app.js
  src/assets/stylesheets/layout/_base.scss
  src/assets/stylesheets/layout/_sidebar.scss
  src/assets/stylesheets/layout/_tabs.scss
  src/templates/full.html.hbs
  src/templates/partials/header.html
  src/templates/sdk.html.hbs
Labels: changelog:enhancements
