Repository kuzzleio/documentation, pull requests merged in 2018-06, with the labels that each got.

#485 Update "guide/essentials/plugins" page
  src/guide/essentials/plugins.md
Labels: changelog:enhancements

#486 Update metadata
  .github/pull_request_template.md
  src/api-documentation/controller-document/get.md
  src/api-documentation/notifications/index.md
  src/guide/essentials/document-metadata.md
  src/guide/essentials/persisted.md
Labels: changelog:new-features

#488 Fix wrong returned value for list indexes request
  src/api-documentation/controller-index/list.md
Labels: changelog:bug-fixes

#461 Add doc for systemd script helper in setupsh
  src/guide/getting-started/index.md
Labels: changelog:new-features
