Repository kuzzleio/documentation, pull requests merged in 2018-07, with the labels that each got.

#492 Replace constructor with authenticator
  src/plugins-reference/plugins-context/accessors.md
  src/plugins-reference/plugins-features/adding-authentication-strategy.md
Labels: changelog:enhancements

#493 Fix dead link
  src/api-documentation/controller-index/get-auto-refresh.md
  src/api-documentation/controller-index/refresh-interval.md
  src/api-documentation/controller-index/refresh.md
  src/api-documentation/controller-index/set-auto-refresh.md
  src/sdk-reference/kuzzle/get-auto-refresh.md
  src/sdk-reference/kuzzle/refresh-index.md
  src/sdk-reference/kuzzle/set-auto-refresh.md
Labels: changelog:bug-fixes

#495 Improve disconnect() documentation
  src/sdk-reference/kuzzle/disconnect.md
Labels: changelog:enhancements

#501 Errors documentation update
  src/api-documentation/errors/index.md
  src/plugins-reference/plugins-context/errors.md
Labels: changelog:enhancements

#499 Fix dead links
  src/api-documentation/controller-auth/login.md
  src/api-documentation/controller-security/get-credentials-by-id.md
  src/api-documentation/notifications/index.md
  src/plugins-reference/plugins-context/accessors.md
  src/plugins-reference/plugins-features/adding-authentication-strategy.md
  src/sdk-reference/essentials/notifications.md
Labels: changelog:bug-fixes

#503 Fix erroneous response example for security:validateCredentials
  src/api-documentation/controller-auth/validate-my-credentials.md
  src/api-documentation/controller-security/validate-credentials.md
  src/sdk-reference/security/validate-credentials.md
Labels: changelog:bug-fixes

#497 New RequestContext version
  src/guide/essentials/request-and-response-format.md
  src/plugins-reference/plugins-context/constructors.md
Labels: changelog:enhancements

#504 SDK: Simpler Kuzzle instance description
  src/sdk-reference/event-emitter/index.md
  src/sdk-reference/kuzzle/index.md
Labels: changelog:enhancements

#506 Security guide update
  index.js
  package-lock.json
  src/api-documentation/notifications/index.md
  src/assets/stylesheets/_versions.scss
  src/guide/essentials/security.md
  src/guide/kuzzle-depth/roles-definitions.md
  src/plugins-reference/plugins-features/adding-authentication-strategy.md
Labels: changelog:bug-fixes

#500 Fix security:search[Roles|Profiles|Users] documentation
  src/api-documentation/controller-security/search-profiles.md
  src/api-documentation/controller-security/search-roles.md
  src/api-documentation/controller-security/search-users.md
  src/sdk-reference/security/search-profiles.md
  src/sdk-reference/security/search-roles.md
  src/sdk-reference/security/search-users.md
Labels: changelog:bug-fixes

#509 Release 1.2.5
  package-lock.json
  package.json
  src/guide/essentials/request-and-response-format.md
  src/plugins-reference/plugins-context/constructors.md
  src/sdk-reference/kuzzle/disconnect.md
Labels: release
