Repository kuzzleio/documentation, pull requests merged in 2018-11, with the labels that each got.

#103 KZL-749 Add scrollTo on left sidebar menu
  src/assets/js/scrollTo.js
Labels: changelog:enhancements

#104 KZL-746 Add rules to indent ToC childrens
  src/assets/stylesheets/layout/_sidebar.scss
Labels: changelog:enhancements

#105 Fix code CSS
  src/assets/stylesheets/base/_typeset.scss
Labels: changelog:bug-fixes

#107 KZL-743 Add sections separator
  src/api/1/controller-admin/index.md
  src/api/1/essentials/connecting-to-kuzzle/index.md
  src/api/1/essentials/errors/index.md
  src/api/1/essentials/index.md
  src/api/1/essentials/kuzzle-response/index.md
  src/api/1/essentials/notifications/index.md
  src/api/1/essentials/query-syntax/index.md
  src/api/1/essentials/volatile-data/index.md
  src/assets/stylesheets/layout/_base.scss
  src/assets/stylesheets/layout/_nav.scss
  src/guide/1/code-examples/index.md
  src/guide/1/dbsearch/android/androidstudio_project_databasesearch.png
  src/guide/1/dbsearch/android/androidstudio_project_noactivity.png
  src/guide/1/dbsearch/android/index.md
  src/guide/1/dbsearch/go/index.md
  src/guide/1/dbsearch/index.md
  src/guide/1/dbsearch/introduction/index.md
  src/guide/1/dbsearch/javascript/index.md
  src/guide/1/essentials/index.md
  src/guide/1/geofencing/android/androidstudio_project_geofencing.png
  src/guide/1/geofencing/android/androidstudio_project_noactivity.png
  src/guide/1/geofencing/android/index.md
  src/guide/1/geofencing/go/index.md
  src/guide/1/geofencing/index.md
  src/guide/1/geofencing/introduction/index.md
  src/guide/1/geofencing/javascript/index.md
  src/guide/1/getting-started/index.md
  src/guide/1/iot/android/androidstudio_project_iot.png
  src/guide/1/iot/android/androidstudio_project_noactivity.png
  src/guide/1/iot/android/index.md
  src/guide/1/iot/go/index.md
  src/guide/1/iot/index.md
  src/guide/1/iot/introduction/index.md
  src/guide/1/iot/javascript/index.md
  src/guide/1/kuzzle-depth/index.md
  src/guide/1/pubsub/android/androidstudio_project_noactivity.png
  src/guide/1/pubsub/android/androidstudio_project_pubsub.png
  src/guide/1/pubsub/android/index.md
  src/guide/1/pubsub/go/index.md
  src/guide/1/pubsub/index.md
  src/guide/1/pubsub/introduction/index.md
  src/guide/1/pubsub/javascript/index.md
  src/templates/partials/nav.html
  src/templates/partials/navMobile.html
Labels: changelog:enhancements

#118 [kuttlefish] Fix PR reporting
  .ci/comment.html
  .travis.yml
Labels: changelog:exclude

#113 KZL-747 algolia on doc v2
  .travis.yml
  config/metalsmith.json
  config/versions.json
  helpers/manageArgs.js
  index.js
  package.json
  src/assets/js/algolia-search.js
  src/assets/js/app.js
  src/assets/stylesheets/layout/_search.scss
  src/templates/partials/loadScript.html
Labels: changelog:enhancements

#120 [optim] Fix automatic redirect rules
  helpers/ancestryHelpers.js
  index.js
  src/plugins/1/index.md
Labels: changelog:enhancements

#119 [optim] Remove site_url from ressource loading
  src/templates/partials/head.html
Labels: changelog:exclude

#121 [CSS] Various CSS fix
  src/assets/stylesheets/base/_typeset.scss
  src/assets/stylesheets/extensions/_alert.scss
  src/assets/stylesheets/extensions/_permalinks.scss
  src/assets/stylesheets/layout/_base.scss
  src/assets/stylesheets/layout/_header.scss
  src/assets/stylesheets/layout/_nav.scss
Labels: changelog:enhancements

#123 [optim] Bundle JS and CSS files
  index.js
  src/assets/js/drawer.js
  src/assets/js/libs/algolia.js
  src/assets/js/libs/jquery.min.js
  src/assets/js/libs/prism.js
  src/assets/js/libs/select2.js
  src/assets/stylesheets/application-palette.scss
  src/assets/stylesheets/libs/_font-awesome.scss
  src/assets/stylesheets/libs/_googleFonts.scss
  src/assets/stylesheets/libs/_material-icons.scss
  src/assets/stylesheets/libs/_monokai.scss
  src/assets/stylesheets/libs/_prism.scss
  src/assets/stylesheets/libs/_select2.scss
  src/assets/stylesheets/main.scss
  src/templates/partials/head.html
  src/templates/partials/loadScript.html
Labels: changelog:enhancements

#124 [CSS] Fix menu on mobile
  src/assets/stylesheets/extensions/_select2.scss
  src/assets/stylesheets/layout/_header.scss
  src/assets/stylesheets/layout/_nav.scss
  src/templates/partials/navMobile.html
  src/templates/sdk.html.hbs
Labels: changelog:enhancements

#127 [ci] Remove unsafe deployment
  .travis.yml
Labels: changelog:exclude

#126 [CSS] Various CSS fix (2)
  src/assets/stylesheets/base/_typeset.scss
  src/assets/stylesheets/extensions/_select2.scss
  src/assets/stylesheets/layout/_header.scss
  src/assets/stylesheets/layout/_tabs.scss
  src/assets/stylesheets/libs/_prism.scss
  src/templates/sdk.html.hbs
Labels: changelog:enhancements

#138 [kuttlefish] FIx logo display in mail
  .ci/comment.html
  src/assets/images/logos/android.png
  src/assets/images/logos/cpp.png
  src/assets/images/logos/csharp.png
  src/assets/images/logos/go.png
  src/assets/images/logos/java.png
  src/assets/images/logos/javascript.png
  src/assets/images/logos/js.png
  src/assets/images/logos/lua.png
  src/assets/images/logos/php.png
  src/assets/images/logos/python.png
  src/assets/images/logos/ruby.png
Labels: changelog:exclude

#136 elasticsearch: imported documentation from doc v1
  plugins/anchors.js
  src/assets/stylesheets/base/_typeset.scss
  src/assets/stylesheets/layout/_base.scss
  src/assets/stylesheets/layout/_nav.scss
  src/guide/1/elasticsearch/basic-queries/index.md
  src/guide/1/elasticsearch/bool-query/index.md
  src/guide/1/elasticsearch/data-insertion/index.md
  src/guide/1/elasticsearch/index.md
  src/guide/1/elasticsearch/installation/index.md
  src/guide/1/elasticsearch/introduction/index.md
  src/guide/1/elasticsearch/useful-commands/index.md
  src/templates/partials/anchors.html
Labels: changelog:new-features

#144 [front] Add top menu active behavior
  src/assets/stylesheets/layout/_tabs.scss
  src/templates/partials/tabs.html
Labels: changelog:enhancements

#137 [ci] Add Vfinder
  .ci/vfinder/exceptions.txt
  .travis.yml
Labels: changelog:enhancements

#156 [sdk-js5] move essentials pages, reorder and add separators
  package-lock.json
  src/sdk-reference/js/5/essentials/index.md
  src/sdk-reference/js/5/events/index.md
  src/sdk-reference/js/5/handling-errors/index.md
  src/sdk-reference/js/5/handling-errors/snippets/handling-errors-1.js
  src/sdk-reference/js/5/kuzzle/index.md
  src/sdk-reference/js/5/notifications/index.md
  src/sdk-reference/js/5/notifications/snippets/notifications-1.js
  src/sdk-reference/js/5/notifications/snippets/notifications-2.js
  src/sdk-reference/js/5/notifications/snippets/notifications-3.js
  src/sdk-reference/js/5/notifications/snippets/notifications-4.js
  src/sdk-reference/js/5/notifications/snippets/notifications-5.js
  src/sdk-reference/js/5/offline-first/index.md
Labels: changelog:enhancements

#168 [build] Add algolia metas automatically
  index.js
Labels: changelog:enhancements
