Repository kuzzleio/documentation, pull requests merged in 2018-12, with the labels that each got.

#134 KZL-744 Koncorde cookbook
  src/assets/images/geolocation/geoBoundingBox.png
  src/assets/images/geolocation/geoDistance.png
  src/assets/images/geolocation/geoDistanceRange.png
  src/assets/images/geolocation/geoPolygon.png
  src/koncorde/1/arrayvalues/index.md
  src/koncorde/1/filter-identifiers/index.md
  src/koncorde/1/geodistances/index.md
  src/koncorde/1/geopoints/index.md
  src/koncorde/1/index.md
  src/koncorde/1/introduction/index.md
  src/koncorde/1/nested/index.md
  src/koncorde/1/operands/index.md
  src/koncorde/1/terms/index.md
  src/koncorde/index.md
  src/templates/partials/tabs.html
Labels: changelog:new-features

#163 [protocol] fix protocol documentation
  src/protocols/1/essentials/getting-started/index.md
Labels: changelog:bug-fixes

#171 [FIX] Add noredirect rule to 404 page
  index.js
  src/404.md
Labels: changelog:bug-fixes

#172 KZL-912 Fix version selector
  src/assets/js/versionSelector.js
Labels: changelog:bug-fixes

#177 [build] Add Webpack to metalsmith build process
  config/webpack.js
  index.js
  package-lock.json
  package.json
  src/assets/js/.eslintrc.json
  src/assets/js/app.js
  src/assets/js/libs/algolia.js
  src/assets/js/libs/jquery.min.js
  src/assets/js/libs/prism.js
  src/assets/js/libs/select2.js
  src/assets/js/main.js
Labels: changelog:new-features

#175 KZL-918 Add tags and sort search results
  helpers/algolia.js
  index.js
  src/assets/js/algolia-search.js
  src/assets/stylesheets/layout/_search.scss
Labels: changelog:new-features

#178 [Front] Fix prismJs highlight language
  config/webpack.js
  package-lock.json
  package.json
  src/assets/js/main.js
  src/assets/js/prism.js
Labels: changelog:bug-fixes

#147 [KZL-761] Add Golang Getting Started page
  src/sdk-reference/go/1/error-handling/index.md
  src/sdk-reference/go/1/getting-started/index.md
  src/sdk-reference/go/1/getting-started/snippets/document.go
  src/sdk-reference/go/1/getting-started/snippets/document.test.yml
  src/sdk-reference/go/1/getting-started/snippets/init.go
  src/sdk-reference/go/1/getting-started/snippets/init.test.yml
  src/sdk-reference/go/1/getting-started/snippets/realtime.go
  src/sdk-reference/go/1/getting-started/snippets/realtime.test.yml
  test/lib/snippet.js
  test/lib/testManager.js
  test/templates/standalone.tpl.go
Labels: changelog:new-features

#182 KZL-945 fix top banner
  src/assets/stylesheets/extensions/_permalinks.scss
  src/assets/stylesheets/layout/_base.scss
  src/assets/stylesheets/layout/_header.scss
  src/assets/stylesheets/layout/_sidebar.scss
  src/templates/partials/betaChip.html
  src/templates/partials/disclaimer.html
  src/templates/partials/header.html
  src/templates/partials/navMobile.html
Labels: changelog:bug-fixes

#183 KZL-913 Fix scrollTo on left menu
  src/assets/js/main.js
  src/assets/js/scrollTo.js
Labels: changelog:bug-fixes

#181 JSv6 - discarded event
  src/sdk-reference/js/6/events/index.md
Labels: changelog:enhancements

#187 [KZL-759] Add Getting started for Java SDK
  src/sdk-reference/java/1/error-handling/index.md
  src/sdk-reference/java/1/getting-started/index.md
  src/sdk-reference/java/1/getting-started/snippets/document.java
  src/sdk-reference/java/1/getting-started/snippets/document.test.yml
  src/sdk-reference/java/1/getting-started/snippets/firstconnection.java
  src/sdk-reference/java/1/getting-started/snippets/firstconnection.test.yml
  src/sdk-reference/java/1/getting-started/snippets/realtime.java
  src/sdk-reference/java/1/getting-started/snippets/realtime.test.yml
  test/templates/standalone.tpl.java
Labels: changelog:new-features

#196 Fixed `body` in searchUsers API example
  src/api/1/controller-security/search-users/index.md
Labels: changelog:bug-fixes

#207 KZL-985 remove js sdk from deps
  src/api/index.md
  src/sdk-reference/index.md
  test/lib/runners/csharpRunner.js
  test/lib/sdk/jsSdk.js
  test/lib/snippet.js
Labels: changelog:bug-fixes
