Repository kuzzleio/documentation, pull requests merged in 2018-05, with the labels that each got.

#470 Add Turbolinks to enable single page application style
  index.js
  src/assets/javascript/analytics.js
  src/assets/javascript/turbolinks.js
  src/layouts/category-childrens.html
  src/partials/common-meta.html
  src/partials/footer-scripts.html
  src/partials/footer-scripts/index.html
  src/partials/side-code.html
Labels: changelog:enhancements

#478 Add documentation for http events
  src/kuzzle-events/http/index.md
  src/sdk-reference/kuzzle/get-my-rights.md
Labels: changelog:new-features

#480 Add documentation for collection/create with a mapping
  src/api-documentation/controller-collection/create.md
Labels: changelog:new-features

#483 Release 1.2.3
  package-lock.json
  package.json
  src/api-documentation/controller-collection/create.md
  src/kuzzle-events/http/index.md
  src/sdk-reference/kuzzle/get-my-rights.md
Labels: release
