Repository kuzzleio/documentation, pull requests merged in 2019-07, with the labels that each got.

#387 Add redirections
  redirections.yml
Labels: changelog:exclude

#391 dont-change-page-on-submenu-click-and-open/close-submenu
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/styles/layout/_nav.scss
Labels: changelog:enhancements

#392 KZL-1212-add-banner-with-external-resources
  src/.vuepress/index-to-algolia/index.js
  src/.vuepress/public/logos/logo-github.svg
  src/.vuepress/public/logos/logo-gitter.svg
  src/.vuepress/public/logos/logo-stack-overflow.svg
  src/.vuepress/public/logos/logo-youtube.svg
  src/.vuepress/theme/ContentFeedback.vue
  src/.vuepress/theme/Footer.vue
  src/.vuepress/theme/Layout.vue
  src/.vuepress/theme/styles/layout/_content.scss
  src/.vuepress/theme/styles/layout/_footer.scss
Labels: changelog:enhancements

#394 fix-sidebar-submenu
  src/.vuepress/theme/Sidebar.vue
Labels: changelog:bug-fixes

#389 KZL-1271-close-sidebar
  package-lock.json
  src/.vuepress/links.json
  src/.vuepress/theme/Header.vue
  src/.vuepress/theme/Layout.vue
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/Tabs.vue
  src/.vuepress/theme/TabsMobile.vue
  src/official-plugins/index.md
  src/sdk/index.md
Labels: changelog:bug-fixes

#393 KZL-1124-add-selector-on-api-page
  src/.vuepress/components/SDKSelector.vue
  src/.vuepress/sdk.json
  src/.vuepress/theme/Layout.vue
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/styles/layout/_sdk-selector.scss
  src/.vuepress/theme/styles/main.scss
Labels: changelog:enhancements

#398 fix-sidebar-and-selector-and-add-csharp
  src/.vuepress/components/SDKSelector.vue
  src/.vuepress/sdk.json
  src/.vuepress/theme/Layout.vue
  src/.vuepress/theme/NotFound.vue
  src/.vuepress/theme/Search.vue
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/styles/layout/_nav.scss
  src/.vuepress/util.js
Labels: changelog:bug-fixes

#395 Fix some frontend bugs, typos and alignements
  src/.vuepress/components/SDKSelector.vue
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/Tabs.vue
  src/.vuepress/theme/TabsMobile.vue
  src/.vuepress/theme/styles/extensions/_tiles.scss
  src/.vuepress/theme/styles/layout/_base.scss
  src/.vuepress/theme/styles/layout/_nav.scss
  src/.vuepress/theme/styles/layout/_tabs.scss
  src/official-plugins/index.md
  src/sdk/index.md
Labels: changelog:enhancements

#399 fix-tabs-and-tabs-mobile
  src/.vuepress/theme/Tabs.vue
  src/.vuepress/theme/TabsMobile.vue
Labels: changelog:bug-fixes

#401 fix-selector-and-loading
  src/.vuepress/components/SDKSelector.vue
  src/.vuepress/theme/Layout.vue
  src/.vuepress/theme/Search.vue
  src/.vuepress/theme/styles/layout/_sidebar.scss
Labels: changelog:bug-fixes

#402 always redirect to home page
  src/.vuepress/components/SDKSelector.vue
Labels: changelog:bug-fixes

#404 fix sidebar by adding a
  src/.vuepress/theme/Sidebar.vue
Labels: changelog:bug-fixes
