Repository kuzzleio/documentation, pull requests merged in 2019-08, with the labels that each got.

#407 Add prod deployment
  .travis.yml
Labels: do not merge

#406 fix fix-indent package remove breaklines
  package.json
  src/.vuepress/markdown/code-snippet.js
  src/.vuepress/markdown/fix-indents.js
Labels: changelog:bug-fixes

#408 Fix right anchor
  src/.vuepress/theme/TOC.vue
Labels: changelog:bug-fixes

#405 Fix command devServer from the CLI for repositories
  .repos/repositories.js
Labels: changelog:bug-fixes

#411 Optimize build with Anchors and cache
  .travis.yml
Labels: changelog:exclude

#412 [ front ] Add homepage
  src/.vuepress/components/Home.vue
  src/.vuepress/public/logos/book.svg
  src/.vuepress/public/logos/brackets.svg
  src/.vuepress/public/logos/extend-sdk/index.md
  src/.vuepress/public/logos/plugin.svg
  src/.vuepress/public/logos/rocket.svg
  src/.vuepress/public/logos/search.svg
  src/.vuepress/public/logos/settings.svg
  src/.vuepress/public/logos/tools.svg
  src/.vuepress/theme/styles/extensions/_tiles.scss
  src/index.md
Labels: changelog:new-features

#413 Add license
  LICENSE.md
Labels: changelog:exclude
