Repository kuzzleio/documentation, pull requests merged in 2019-06, with the labels that each got.

#300 Add page about bulk:write and bulk:mwrite
  src/core/1/api/api-reference/controller-bulk/m-write/index.md
  src/core/1/api/api-reference/controller-bulk/write/index.md
  src/core/1/guide/guides/essentials/data-validation/index.md
  src/core/1/guide/guides/essentials/document-metadata/index.md
Labels: changelog:new-features, v3

#311 Add PDF sending example for Request.setResult
  src/core/1/plugins/plugin-context/constructors/request/index.md
Labels: v3

#304 fix sdk js tests
  .gitignore
  .travis.yml
  docker/js
  src/sdk/js/6/controllers/bulk/import/snippets/import.js
  src/sdk/js/6/core-classes/kuzzle/use-controller/snippets/use-controller.js
  src/sdk/js/6/essentials/getting-started/raw-web/snippets/create.html
  test/lib/runners/webpackRunner.js
  test/lib/sdk/jsSdk.js
Labels: changelog:bug-fixes, v3

#318 Remove debug
  src/core/1/guides/getting-started/first-steps/index.md
Labels: changelog:bug-fixes, changelog:exclude

#301 Deprecate realtime join
  src/core/1/api/controllers/realtime/join/index.md
Labels: changelog:enhancements, v3

#296 Rewrite the Realtime guide
  .gitignore
  src/core/1/api/essentials/notifications/index.md
  src/core/1/api/essentials/volatile-data/index.md
  src/core/1/guides/essentials/real-time/index.md
  src/core/1/guides/essentials/real-time/pub-sub.png
  src/core/1/guides/essentials/real-time/snippets/subscribe-filter.js
  src/core/1/guides/essentials/real-time/snippets/subscribe-filter.test.yml
  src/core/1/guides/essentials/real-time/snippets/subscribe-no-filter.js
  src/core/1/guides/essentials/real-time/snippets/subscribe-no-filter.test.yml
  src/core/1/guides/essentials/real-time/snippets/subscribe-options.js
  src/core/1/guides/essentials/real-time/snippets/subscribe-options.test.yml
  src/core/1/guides/essentials/real-time/subscription-filter-scope.png
  src/sdk/cpp/1/essentials/realtime-notifications/index.md
  src/sdk/go/1/essentials/realtime-notifications/index.md
  src/sdk/java/1/essentials/realtime-notifications/index.md
  src/sdk/js/6/essentials/realtime-notifications/index.md
Labels: changelog:enhancements, v3

#319 getting-started-sdk-JS6-architecture
  src/sdk/js/6/controllers/index.md
  src/sdk/js/6/core-classes/index.md
  src/sdk/js/6/essentials/index.md
  src/sdk/js/6/getting-started/index.md
  src/sdk/js/6/getting-started/node-js/index.md
  src/sdk/js/6/getting-started/node-js/snippets/create.js
  src/sdk/js/6/getting-started/node-js/snippets/create.test.yml
  src/sdk/js/6/getting-started/node-js/snippets/init.js
  src/sdk/js/6/getting-started/node-js/snippets/init.test.yml
  src/sdk/js/6/getting-started/node-js/snippets/load-sdk.js
  src/sdk/js/6/getting-started/node-js/snippets/load-sdk.test.yml
  src/sdk/js/6/getting-started/node-js/snippets/prepare-db.js
  src/sdk/js/6/getting-started/node-js/snippets/prepare-db.test.yml
  src/sdk/js/6/getting-started/node-js/snippets/subscribe.js
  src/sdk/js/6/getting-started/node-js/snippets/subscribe.test.yml
  src/sdk/js/6/getting-started/raw-web/index.md
  src/sdk/js/6/getting-started/raw-web/snippets/create.html
  src/sdk/js/6/getting-started/raw-web/snippets/create.test.yml
  src/sdk/js/6/getting-started/raw-web/snippets/load-sdk.html
  src/sdk/js/6/getting-started/raw-web/snippets/load-sdk.test.yml
  src/sdk/js/6/getting-started/raw-web/snippets/prepare-db.html
  src/sdk/js/6/getting-started/raw-web/snippets/prepare-db.test.yml
  src/sdk/js/6/getting-started/raw-web/snippets/subscribe.html
  src/sdk/js/6/getting-started/raw-web/snippets/subscribe.test.yml
  src/sdk/js/6/getting-started/webpack/index.md
  src/sdk/js/6/getting-started/webpack/snippets/create.js
  src/sdk/js/6/getting-started/webpack/snippets/create.test.yml
  src/sdk/js/6/getting-started/webpack/snippets/init-kuzzle.js
  src/sdk/js/6/getting-started/webpack/snippets/init-kuzzle.test.yml
  src/sdk/js/6/getting-started/webpack/snippets/subscribe.js
  src/sdk/js/6/getting-started/webpack/snippets/subscribe.test.yml
  src/sdk/js/6/protocols/index.md
Labels: v3

#314 Add a clustering guide
  src/core/1/guides/essentials/plugins/index.md
  src/core/1/guides/kuzzle-depth/scalability/index.md
Labels: Guide, v3

#317 Add new way for updateSpecifications & validateSpecifications
  src/core/1/api/controllers/collection/update-specifications/index.md
  src/core/1/api/controllers/collection/validate-specifications/index.md
Labels: changelog:enhancements, v3

#320 Kzl 1154 ci build
  .ci/comment.html
  .ci/comment_pr.sh
  .travis.yml
  package-lock.json
  package.json
Labels: changelog:exclude

#322 Fix remaining dead links and add check_link to CI
  .travis.yml
  check_link.rb
  src/core/1/api/essentials/volatile-data/index.md
  src/core/1/guides/cookbooks/elasticsearch/installation/index.md
  src/core/1/guides/essentials/configuration/index.md
  src/core/1/guides/essentials/data-validation/index.md
  src/core/1/guides/essentials/installing-kuzzle/index.md
  src/core/1/guides/kuzzle-depth/request-life-cycle/index.md
  src/core/1/plugins/essentials/getting-started/index.md
  src/core/1/plugins/guides/pipes/index.md
  src/core/1/protocols/native-protocols/mqtt/index.md
  src/sdk/cpp/1/controllers/collection/search-specifications/index.md
  src/sdk/cpp/1/controllers/document/search/index.md
  src/sdk/java/1/essentials/getting-started/index.md
  src/sdk/js/6/getting-started/webpack/index.md
Labels: changelog:bug-fixes

#316 Sdks authenticated connected props
  src/sdk/js/6/core-classes/kuzzle/properties/index.md
  src/sdk/js/6/protocols/http/properties/index.md
  src/sdk/js/6/protocols/socketio/properties/index.md
  src/sdk/js/6/protocols/websocket/properties/index.md
Labels: changelog:enhancements, v3

#325 Adapt legacy redirection
  redirections.yml
Labels: changelog:bug-fixes

#324 Update Redis version
  src/core/1/guides/code-examples/iot/introduction/index.md
  src/core/1/guides/essentials/configuration/index.md
  src/core/1/guides/essentials/installing-kuzzle/index.md
Labels: changelog:enhancements

#298 Fix bulk import return
  src/core/1/api/controllers/bulk/import/index.md
  src/sdk/js/6/controllers/bulk/import/index.md
  src/sdk/js/6/controllers/bulk/import/snippets/import.js
Labels: changelog:bug-fixes, v3

#321 Add guide about secrets management with the Vault
  src/core/1/guides/essentials/secrets-vault/index.md
  src/core/1/plugins/plugin-context/secrets/index.md
Labels: changelog:new-features

#333 Restore auth:refreshToken documentation
  src/core/1/api/controllers/auth/refresh-token/index.md
Labels: changelog:bug-fixes

#328 Disable Java and C++ tests
  .travis.yml
Labels: changelog:exclude

#330 Small fixes
  src/core/1/guides/essentials/real-time/index.md
  src/core/1/guides/essentials/secrets-vault/index.md
Labels: changelog:exclude

#299 Documentation for wildcard events
  package-lock.json
  run-all-snippet-tests.sh
  src/.vuepress/util.js
  src/core/1/plugins/guides/events/wildcard-events/index.md
Labels: changelog:new-features, v3

#340 [HOTFIX] Redirect branches to first page
  src/.vuepress/theme/Layout.vue
  src/core/1/guides/code-examples/dbsearch/index.md
  src/core/1/guides/code-examples/geofencing/index.md
  src/core/1/guides/code-examples/iot/index.md
  src/core/1/guides/code-examples/pubsub/index.md
  src/core/1/guides/cookbooks/datavalidation/index.md
  src/core/1/guides/cookbooks/elasticsearch/index.md
  src/core/1/guides/essentials/index.md
  src/core/1/guides/getting-started/index.md
  src/core/1/guides/index.md
  src/core/1/guides/kuzzle-depth/index.md
  src/index.md
Labels: changelog:bug-fixes

#352 [fix] Social links in the footer
  src/.vuepress/theme/Layout.vue
Labels: changelog:bug-fixes

#329 Explain that accessors.sdk and accessors.execute do not trigger events
  check_link.rb
  src/core/1/plugins/guides/events/wildcard-events/index.md
  src/core/1/plugins/plugin-context/accessors/execute/index.md
  src/core/1/plugins/plugin-context/accessors/sdk/index.md
Labels: changelog:enhancements

#355 [feature] Identifiable partial snippets
  .vscode/launch.json
  src/.vuepress/config.js
  src/.vuepress/markdown/code-snippet.js
  src/sdk/java/1/controllers/realtime/subscribe/index.md
  src/sdk/js/6/getting-started/webpack/index.md
  src/sdk/js/6/getting-started/webpack/snippets/init-kuzzle.js
Labels: changelog:new-features

#356 [evol] 's' for Search
  src/.vuepress/theme/Search.vue
Labels: changelog:enhancements

#358 Do not require a git tag to deploy to production
  .travis.yml
Labels: changelog:exclude

#366 [plugins] Fix invalid example: cannot assign to a const variable
  src/core/1/plugins/plugin-context/accessors/execute/index.md
Labels: changelog:bug-fixes

#360 [evol] Universal comment support in snippet extraction tags
  README.md
  src/.vuepress/markdown/code-snippet.js
Labels: changelog:exclude

#367 Update module dependencies to solve security issues
  package-lock.json
  package.json
  src/sdk/cpp/1/core-classes/search-result/getters/index.md
Labels: changelog:enhancements

#361 Development Docker image
  Dockerfile
  package-lock.json
  package.json
Labels: changelog:exclude

#371 [feature] Force snippet language
  README.md
  src/.vuepress/markdown/code-snippet.js
Labels: changelog:exclude

#378 [fix] images in koncorde filter terms
  src/.vuepress/public/geolocation/geoBoundingBox.png
  src/.vuepress/public/geolocation/geoDistance.png
  src/.vuepress/public/geolocation/geoDistanceRange.png
  src/.vuepress/public/geolocation/geoPolygon.png
  src/core/1/koncorde/essentials/terms/index.md
Labels: changelog:exclude

#377 [feature] Fix indent in imported code snippets
  package-lock.json
  package.json
  src/.vuepress/markdown/code-snippet.js
Labels: changelog:enhancements

#376 [feature] Highlight lines in code-snippets
  src/.vuepress/markdown/copy-paste-snippet-btn.js
  src/.vuepress/theme/styles/_config.scss
  src/.vuepress/theme/styles/base/_typeset.scss
  src/.vuepress/theme/styles/libs/_prism.scss
  src/core/1/guides/getting-started/first-steps/index.md
Labels: changelog:exclude
