Repository kuzzleio/documentation, pull requests merged in 2019-03, with the labels that each got.

#249 Better example for SearchResult.next
  src/sdk-reference/js/6/search-result/next/snippets/scroll.js
Labels: changelog:enhancements

#251 fix ssl option name for android
  src/sdk-reference/android/3/kuzzle/constructor/index.md
Labels: changelog:bug-fixes

#255 Document missing getters about offline queue and reconnection options
  .prettierignore
  docker/js
  package-lock.json
  src/sdk-reference/android/3/kuzzle/constructor/index.md
  src/sdk-reference/cpp/1/kuzzle/getters/index.md
  src/sdk-reference/cpp/1/kuzzle/getters/snippets/getters.cpp
  src/sdk-reference/cpp/1/kuzzle/setters/index.md
  src/sdk-reference/cpp/1/kuzzle/setters/snippets/setters.cpp
  src/sdk-reference/js/6/getting-started/webpack/index.md
  src/sdk-reference/js/6/getting-started/webpack/snippets/create.js
  src/sdk-reference/js/6/getting-started/webpack/snippets/create.test.yml
  src/sdk-reference/js/6/getting-started/webpack/snippets/init-kuzzle.js
  src/sdk-reference/js/6/getting-started/webpack/snippets/init-kuzzle.test.yml
  src/sdk-reference/js/6/getting-started/webpack/snippets/subscribe.js
  src/sdk-reference/js/6/getting-started/webpack/snippets/subscribe.test.yml
  src/sdk-reference/js/6/search-result/next/snippets/scroll.js
  test/lib/runners/webpackRunner.js
  test/lib/scripts/puppeteer.js
  test/lib/sdk/jsSdk.js
  test/templates/createDocumentAfterSnippet.tpl.js
  test/templates/doIt.tpl.js
Labels: changelog:new-features

#253 Plugin embedded sdk
  src/guide/1/getting-started/running-kuzzle/index.md
  src/plugins/1/accessors/index.md
  src/plugins/1/accessors/sdk/index.md
  src/plugins/1/essentials/getting-started/index.md
  src/sdk-reference/cpp/1/search-result/introduction/index.md
Labels: changelog:enhancements

#252 Add loading of fixtures mappings securities in admin controller
  src/api/1/controller-admin/load-fixtures/index.md
  src/api/1/controller-admin/load-mappings/index.md
  src/api/1/controller-admin/load-securities/index.md
  src/api/1/controller-admin/reset-cache/index.md
  src/api/1/controller-admin/reset-database/index.md
  src/api/1/controller-admin/reset-security/index.md
  src/guide/1/essentials/cli/index.md
  src/guide/1/essentials/signal_handling/index.md
Labels: changelog:enhancements

#270 Release 2.1.0
  index.js
  package-lock.json
  package.json
  src/api/1/controller-admin/load-fixtures/index.md
  src/api/1/controller-admin/load-mappings/index.md
  src/api/1/controller-admin/load-securities/index.md
  src/api/1/controller-admin/reset-cache/index.md
  src/api/1/controller-admin/reset-database/index.md
  src/api/1/controller-admin/reset-security/index.md
  src/api/1/controller-auth/refresh-token/index.md
  src/guide/1/essentials/cli/index.md
  src/guide/1/essentials/signal_handling/index.md
  src/guide/1/getting-started/running-kuzzle/index.md
  src/plugins/1/accessors/index.md
  src/plugins/1/accessors/sdk/index.md
  src/plugins/1/essentials/getting-started/index.md
  src/sdk-reference/cpp/1/search-result/introduction/index.md
  src/sdk-reference/js/6/getting-started/node-js/snippets/subscribe.js
  src/sdk-reference/js/6/getting-started/node-js/snippets/subscribe.test.yml
  test/lib/helpers/logger.js
  test/lib/runners/baseRunner.js
  test/templates/empty-realtime.tpl.js
Labels: release

#267 remove http and socketio pages
  src/sdk-reference/go/1/protocols/http/index.md
  src/sdk-reference/go/1/protocols/socketio/index.md
  src/sdk-reference/java/1/protocol/http/index.md
  src/sdk-reference/java/1/protocol/socketio/index.md
Labels: changelog:bug-fixes

#271 Add documentation page about mappings
  helpers/handlebars.js
  src/api/1/controller-collection/create/index.md
  src/api/1/controller-collection/get-mapping/index.md
  src/api/1/controller-collection/update-mapping/index.md
  src/guide/1/essentials/database-mappings/index.md
  src/guide/1/essentials/persisted/index.md
  src/sdk-reference/cpp/1/collection/create/index.md
  src/sdk-reference/cpp/1/collection/create/snippets/create.cpp
  src/sdk-reference/cpp/1/collection/get-mapping/index.md
  src/sdk-reference/cpp/1/collection/get-mapping/snippets/get-mapping.cpp
  src/sdk-reference/cpp/1/collection/update-mapping/index.md
  src/sdk-reference/cpp/1/collection/update-mapping/snippets/update-mapping.cpp
  src/sdk-reference/go/1/collection/create/index.md
  src/sdk-reference/go/1/collection/create/snippets/create.go
  src/sdk-reference/go/1/collection/update-mapping/index.md
  src/sdk-reference/go/1/collection/update-mapping/snippets/update-mapping.go
  src/sdk-reference/js/6/collection/create/index.md
  src/sdk-reference/js/6/collection/create/snippets/create.js
  src/sdk-reference/js/6/collection/get-mapping/index.md
  src/sdk-reference/js/6/collection/get-mapping/snippets/get-mapping.js
  src/sdk-reference/js/6/collection/update-mapping/index.md
  src/sdk-reference/js/6/collection/update-mapping/snippets/update-mapping.js
Labels: changelog:enhancements
