Repository kuzzleio/documentation, pull requests merged in 2019-04, with the labels that each got.

#269 CPP/JS: Update offline tools
  src/guide/1/essentials/signal-handling/index.md
  src/sdk-reference/cpp/1/kuzzle/constructor/index.md
  src/sdk-reference/cpp/1/kuzzle/getters/snippets/getters.cpp
  src/sdk-reference/cpp/1/offline-tools/index.md
  src/sdk-reference/js/6/offline-tools/index.md
Labels: changelog:enhancements

#278 [JS SDK] auth:createCredentials does not return the password
  src/sdk-reference/js/6/auth/create-my-credentials/snippets/create-my-credentials.js
  src/sdk-reference/js/6/auth/get-my-credentials/snippets/get-my-credentials.js
Labels: changelog:bug-fixes

#280 doc: disambiguation of getMapping sample response in JS SDK
  src/sdk-reference/js/6/collection/get-mapping/index.md
  src/sdk-reference/js/6/collection/get-mapping/snippets/get-mapping.js
Labels: changelog:bug-fixes

#277 JS SDK: document class properties independently to the "introduction" pages
  src/sdk-reference/js/6/auth/login/index.md
  src/sdk-reference/js/6/auth/logout/index.md
  src/sdk-reference/js/6/auth/refresh-token/index.md
  src/sdk-reference/js/6/kuzzle-error/introduction/index.md
  src/sdk-reference/js/6/kuzzle-error/properties/index.md
  src/sdk-reference/js/6/kuzzle/introduction/index.md
  src/sdk-reference/js/6/kuzzle/properties/index.md
  src/sdk-reference/js/6/offline-tools/index.md
  src/sdk-reference/js/6/profile/introduction/index.md
  src/sdk-reference/js/6/profile/properties/index.md
  src/sdk-reference/js/6/role/introduction/index.md
  src/sdk-reference/js/6/role/properties/index.md
  src/sdk-reference/js/6/search-result/introduction/index.md
  src/sdk-reference/js/6/search-result/properties/index.md
  src/sdk-reference/js/6/socketio/introduction/index.md
  src/sdk-reference/js/6/socketio/properties/index.md
  src/sdk-reference/js/6/user/introduction/index.md
  src/sdk-reference/js/6/user/properties/index.md
  src/sdk-reference/js/6/websocket/introduction/index.md
  src/sdk-reference/js/6/websocket/properties/index.md
Labels: changelog:enhancements

#283 Fix erroneous bulk:import example
  src/api/1/controller-bulk/import/index.md
Labels: API
