Repository kuzzleio/documentation, pull requests merged in 2019-05, with the labels that each got.

#292 Add since
  src/sdk-reference/js/6/extend-sdk/index.md
Labels: changelog:enhancements

#293 [KZL-1036] Add available plugins
  src/assets/images/logos/cluster.svg
  src/assets/images/logos/computed.svg
  src/assets/images/logos/logger.svg
  src/assets/images/logos/passport.svg
  src/assets/images/logos/probe.svg
  src/assets/stylesheets/extensions/_tiles.scss
  src/assets/stylesheets/main.scss
  src/plugins/1/essentials/available-plugins/index.md
  src/sdk-reference/index.md
Labels: changelog:complements

#294 add s3 plugin
  src/assets/images/logos/plugin-s3.svg
  src/plugins/1/essentials/available-plugins/index.md
Labels: changelog:enhancements

#291 Getting started React + improve snippetManager
  package.json
  plugins/snippetManager.js
  src/sdk-reference/js/6/getting-started/node-js/snippets/subscribe.js
  src/sdk-reference/js/6/getting-started/react/index.md
  src/sdk-reference/js/6/getting-started/react/snippets/init.js
  src/sdk-reference/js/6/getting-started/react/snippets/init.test.yml
  src/sdk-reference/js/6/getting-started/react/snippets/search.js
  src/sdk-reference/js/6/getting-started/react/snippets/search.test.yml
  src/sdk-reference/js/6/getting-started/react/snippets/subscribe.js
  src/sdk-reference/js/6/getting-started/react/snippets/subscribe.test.yml
  test/templates/success.tpl.js
Labels: changelog:enhancements

#303 Port #274 to 3-dev
  src/core/1/api/api-reference/controller-auth/check-token/index.md
  src/sdk/js/6/controllers/auth/check-token/index.md
Labels: v3

#305 Port #275 to 3-dev
  src/core/1/guide/guides/essentials/security/index.md
  src/core/1/guide/guides/essentials/user-authentication/index.md
  src/core/1/guide/guides/kuzzle-depth/roles-definitions/index.md
Labels: v3

#310 Port #277 to 3-dev
  src/core/1/plugins/plugin-context/accessors/index.md
  src/core/1/plugins/plugin-context/constructors/index.md
  src/core/1/plugins/plugin-context/errors/index.md
  src/core/1/plugins/plugin-context/log/index.md
  src/sdk/js/6/controllers/auth/login/index.md
  src/sdk/js/6/controllers/auth/logout/index.md
  src/sdk/js/6/controllers/auth/refresh-token/index.md
  src/sdk/js/6/controllers/auth/refresh-token/snippets/refreshToken.js
  src/sdk/js/6/controllers/auth/refresh-token/snippets/refreshToken.test.yml
  src/sdk/js/6/core-classes/kuzzle-error/introduction/index.md
  src/sdk/js/6/core-classes/kuzzle-error/properties/index.md
  src/sdk/js/6/core-classes/kuzzle-event-emitter/introduction/index.md
  src/sdk/js/6/core-classes/kuzzle/constructor/index.md
  src/sdk/js/6/core-classes/kuzzle/introduction/index.md
  src/sdk/js/6/core-classes/kuzzle/properties/index.md
  src/sdk/js/6/core-classes/profile/introduction/index.md
  src/sdk/js/6/core-classes/profile/properties/index.md
  src/sdk/js/6/core-classes/role/introduction/index.md
  src/sdk/js/6/core-classes/role/properties/index.md
  src/sdk/js/6/core-classes/search-result/introduction/index.md
  src/sdk/js/6/core-classes/search-result/properties/index.md
  src/sdk/js/6/core-classes/user/introduction/index.md
  src/sdk/js/6/core-classes/user/properties/index.md
  src/sdk/js/6/essentials/offline-tools/index.md
  src/sdk/js/6/protocols/http/constructor/index.md
  src/sdk/js/6/protocols/http/introduction/index.md
  src/sdk/js/6/protocols/socketio/constructor/index.md
  src/sdk/js/6/protocols/socketio/introduction/index.md
  src/sdk/js/6/protocols/socketio/properties/index.md
  src/sdk/js/6/protocols/websocket/constructor/index.md
  src/sdk/js/6/protocols/websocket/introduction/index.md
  src/sdk/js/6/protocols/websocket/properties/index.md
Labels: v3

#312 Port 278 to 3-dev
  src/sdk/js/6/controllers/auth/create-my-credentials/snippets/create-my-credentials.js
  src/sdk/js/6/controllers/auth/get-my-credentials/snippets/get-my-credentials.js
Labels: v3

#306 Port #280 to 3-dev
  src/sdk/js/6/controllers/collection/get-mapping/snippets/get-mapping.js
Labels: v3

#307 Port #282 to 3-dev
  src/sdk/go/1/controllers/index/refresh-internal/index.md
  src/sdk/java/1/controllers/index/refresh-internal/index.md
  src/sdk/js/6/controllers/index/refresh-internal/index.md
Labels: v3

#308 Port #283 to 3-dev
  src/core/1/api/api-reference/controller-bulk/import/index.md
Labels: v3

#309 Port #284 to 3-dev
  src/sdk/js/6/core-classes/base-controller/index.md
  src/sdk/js/6/core-classes/base-controller/introduction/index.md
  src/sdk/js/6/core-classes/base-controller/properties/index.md
  src/sdk/js/6/core-classes/base-controller/query/index.md
  src/sdk/js/6/core-classes/kuzzle/index.md
  src/sdk/js/6/core-classes/kuzzle/query/index.md
  src/sdk/js/6/core-classes/kuzzle/use-controller/index.md
  src/sdk/js/6/core-classes/kuzzle/use-controller/snippets/use-controller.js
  src/sdk/js/6/core-classes/kuzzle/use-controller/snippets/use-controller.test.yml
Labels: v3
