Repository kuzzleio/documentation, pull requests merged in 2019-02, with the labels that each got.

#215 KZL-966 Getting started with vanilla browser
  README.md
  config/webpack.js
  src/sdk-reference/js/6/getting-started/raw-web/index.md
  src/sdk-reference/js/6/getting-started/raw-web/snippets/create.html
  src/sdk-reference/js/6/getting-started/raw-web/snippets/create.test.yml
  src/sdk-reference/js/6/getting-started/raw-web/snippets/load-sdk.html
  src/sdk-reference/js/6/getting-started/raw-web/snippets/load-sdk.test.yml
  src/sdk-reference/js/6/getting-started/raw-web/snippets/prepare-db.html
  src/sdk-reference/js/6/getting-started/raw-web/snippets/prepare-db.test.yml
  src/sdk-reference/js/6/getting-started/raw-web/snippets/subscribe.html
  src/sdk-reference/js/6/getting-started/raw-web/snippets/subscribe.test.yml
  src/sdk-reference/js/6/getting-started/raw-web/snippets/try.html
  src/sdk-reference/js/6/getting-started/raw-web/snippets/try.test.yml
  test/lib/scripts/puppeteer.js
Labels: changelog:new-features

#232 [test] Fix C++ realtime tests
  src/sdk-reference/cpp/1/getting-started/snippets/realtime.cpp
  src/sdk-reference/cpp/1/realtime/count/snippets/count.cpp
  src/sdk-reference/cpp/1/realtime/subscribe/snippets/document-notifications-leave-scope.cpp
  src/sdk-reference/cpp/1/realtime/subscribe/snippets/document-notifications.cpp
  src/sdk-reference/cpp/1/realtime/subscribe/snippets/message-notifications.cpp
  src/sdk-reference/cpp/1/realtime/subscribe/snippets/user-notifications.cpp
  src/sdk-reference/cpp/1/realtime/unsubscribe/snippets/unsubscribe.cpp
Labels: changelog:bug-fixes

#229 Add community SDKs section
  src/assets/images/logos/dart.svg
  src/assets/images/logos/rust.svg
  src/assets/stylesheets/extensions/_languages.scss
  src/sdk-reference/index.md
Labels: changelog:enhancements

#230 Add footer social links
  index.js
  src/templates/partials/footer.html
Labels: changelog:enhancements

#234 Doc guide js5 to js6
  src/guide/1/geofencing/javascript/index.md
  src/guide/1/geofencing/javascript/snippets/createdoc.js
  src/guide/1/geofencing/javascript/snippets/createdoc.test.yml
  src/guide/1/geofencing/javascript/snippets/definearea.js
  src/guide/1/geofencing/javascript/snippets/definearea.test.yml
  src/guide/1/geofencing/javascript/snippets/geofenc.js
  src/guide/1/geofencing/javascript/snippets/geofenc.test.yml
  src/guide/1/geofencing/javascript/snippets/load-sdk.js
  src/guide/1/geofencing/javascript/snippets/load-sdk.test.yml
  src/guide/1/geofencing/javascript/snippets/location.js
  src/guide/1/geofencing/javascript/snippets/location.test.yml
  src/guide/1/geofencing/javascript/snippets/subscribe.js
  src/guide/1/geofencing/javascript/snippets/subscribe.test.yml
  src/guide/1/geofencing/javascript/snippets/updatedoc.js
  src/guide/1/geofencing/javascript/snippets/updatedoc.test.yml
  src/guide/1/getting-started/first-steps/index.md
  src/guide/1/getting-started/first-steps/snippets/create.js
  src/guide/1/getting-started/first-steps/snippets/create.test.yml
  src/guide/1/getting-started/first-steps/snippets/init-sample.js
  src/guide/1/getting-started/first-steps/snippets/init-sample.test.yml
  src/guide/1/getting-started/first-steps/snippets/init.js
  src/guide/1/getting-started/first-steps/snippets/init.test.yml
  src/guide/1/getting-started/first-steps/snippets/load-sdk.js
  src/guide/1/getting-started/first-steps/snippets/load-sdk.test.yml
  src/guide/1/getting-started/first-steps/snippets/subscribe.js
  src/guide/1/getting-started/first-steps/snippets/subscribe.test.yml
  src/guide/1/pubsub/javascript/index.md
  src/guide/1/pubsub/javascript/snippets/load-sdk.js
  src/guide/1/pubsub/javascript/snippets/load-sdk.test.yml
  src/guide/1/pubsub/javascript/snippets/publish.js
  src/guide/1/pubsub/javascript/snippets/publish.test.yml
  src/guide/1/pubsub/javascript/snippets/pubsubjs.js
  src/guide/1/pubsub/javascript/snippets/pubsubjs.test.yml
  src/guide/1/pubsub/javascript/snippets/subscribe.js
  src/guide/1/pubsub/javascript/snippets/subscribe.test.yml
  src/links_ignore.json
  src/sdk-reference/js/6/getting-started/node-js/index.md
Labels: changelog:enhancements

#235 KZL-1010 Open issue on GitHub
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/content_request.md
  index.js
  src/assets/stylesheets/layout/_content.scss
  src/templates/full.html.hbs
  src/templates/partials/contentFeedback.html
  src/templates/sdk.html.hbs
Labels: changelog:new-features

#239 Add Google Analytics
  src/templates/partials/head.html
Labels: changelog:enhancements

#243 Remove all @beta tag in JS SDK installation guides
  src/guide/1/essentials/user-authentication/index.md
  src/guide/1/geofencing/javascript/index.md
  src/guide/1/getting-started/first-steps/index.md
  src/guide/1/pubsub/javascript/index.md
  src/plugins/1/events/api-events/index.md
  src/plugins/1/events/intro/index.md
  src/plugins/1/events/plugin-events/index.md
  src/sdk-reference/js/6/getting-started/node-js/index.md
Labels: changelog:enhancements

#244 Release update
  src/templates/partials/head.html
  src/templates/partials/header.html
  src/templates/partials/loadScript.html
Labels: do not merge

#245 [hotfix] KZL-1021 Fix algolia links
  src/templates/partials/loadScript.html
Labels: changelog:bug-fixes

#164 KZL-861 Getting started with Webpack
  .prettierignore
  docker/js
  package-lock.json
  src/sdk-reference/js/6/getting-started/webpack/index.md
  src/sdk-reference/js/6/getting-started/webpack/snippets/create.js
  src/sdk-reference/js/6/getting-started/webpack/snippets/create.test.yml
  src/sdk-reference/js/6/getting-started/webpack/snippets/init-kuzzle.js
  src/sdk-reference/js/6/getting-started/webpack/snippets/init-kuzzle.test.yml
  src/sdk-reference/js/6/getting-started/webpack/snippets/subscribe.js
  src/sdk-reference/js/6/getting-started/webpack/snippets/subscribe.test.yml
  src/templates/partials/loadScript.html
  test/lib/runners/webpackRunner.js
  test/lib/scripts/puppeteer.js
  test/lib/sdk/jsSdk.js
  test/templates/createDocumentAfterSnippet.tpl.js
  test/templates/doIt.tpl.js
Labels: changelog:new-features
