Repository kuzzleio/documentation, pull requests merged in 2020-12, with the labels that each got.

#505 Add custom badge component
  README.md
  src/.vuepress/components/CustomBadge.vue
Labels: changelog:new-features

#497 Deprecate the documentation for java-SDK-3
  src/.vuepress/components/DeprecatedBanner.vue
  src/.vuepress/components/JavaDeprecatedBanner.vue
  src/.vuepress/components/Redirect.vue
  src/.vuepress/components/SDKIndex.vue
  src/.vuepress/components/WarningBanner.vue
  src/.vuepress/sections.json
  src/.vuepress/sections.schema.json
  src/.vuepress/theme/Layout.vue
  src/.vuepress/theme/styles/extensions/_alert.scss
  src/.vuepress/theme/styles/extensions/_ribbon.scss
Labels: changelog:enhancements

#506 [Algolia] Hitting production search index
  src/.vuepress/theme/Search.vue
Labels: changelog:exclude

#504 Custom algolia search on mobile
  src/.vuepress/theme/styles/layout/_search.scss
Labels: changelog:enhancements

#503 Add missing sidebar on page 404 on mobile
  src/.vuepress/theme/NotFound.vue
  src/.vuepress/theme/Sidebar.vue
Labels: changelog:bug-fixes

#510 Remove dropdown list item icons
  src/.vuepress/components/MenuDropdown.vue
  src/.vuepress/theme/styles/extensions/_menuDropdown.scss
Labels: changelog:enhancements

#511 Fix scroll to anchor on chrome
  src/.vuepress/theme/Layout.vue
Labels: changelog:bug-fixes

#513 Fix SDK Go V3 documentation not deployed
  src/.vuepress/sections.json
Labels: changelog:bug-fixes

#516 [HOTFIX] remove unreleased SDK from SDK-selector list
  src/.vuepress/theme/Layout.vue
Labels: changelog:bug-fixes
