Repository kuzzleio/documentation, pull requests merged in 2020-11, with the labels that each got.

#479 Replace custom search with Algolia widget
  src/.vuepress/theme/Search.vue
Labels: changelog:enhancements

#483 Selective section release
  src/.vuepress/components/HowToIndex.vue
  src/.vuepress/components/PluginsIndex.vue
  src/.vuepress/components/SDKIndex.vue
  src/.vuepress/config.js
  src/.vuepress/sections.json
  src/.vuepress/sections.schema.json
Labels: changelog:enhancements

#486 [Algolia] Disable legacy search
  src/.vuepress/config.js
  src/.vuepress/index-to-algolia/index.js
Labels: changelog:exclude

#484 Replace the tab plugin
  README.md
  package-lock.json
  package.json
  src/.vuepress/config.js
  src/.vuepress/theme/styles/layout/_sdk-tabs.scss
  src/.vuepress/theme/styles/layout/_tabs.scss
  src/.vuepress/theme/styles/main.scss
Labels: changelog:enhancements

#488 [css] Small UI fixes
  src/.vuepress/theme/styles/base/_typeset.scss
  src/.vuepress/theme/styles/extensions/_alert.scss
Labels: changelog:bug-fixes

#490 Update top menu links + fix menu on mobile/tablet
  src/.vuepress/theme/Tabs.vue
  src/.vuepress/theme/styles/layout/_tabs.scss
Labels: changelog:enhancements

#491 Add major version selector on mobile/tablets
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/styles/layout/_sdk-selector.scss
Labels: changelog:enhancements

#496 better anchors links
  src/.vuepress/config.js
  src/.vuepress/theme/styles/extensions/_permalinks.scss
Labels: changelog:enhancements

#498 New header
  src/.vuepress/theme/Tabs.vue
Labels: changelog:new-features

#499 New top menu structure
  src/.vuepress/components/MenuDropdown.vue
  src/.vuepress/components/SDKSelector.vue
  src/.vuepress/sdk.json
  src/.vuepress/sections.json
  src/.vuepress/theme/Header.vue
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/Tabs.vue
  src/.vuepress/theme/TopMenu.vue
  src/.vuepress/theme/TopMenuV1.vue
  src/.vuepress/theme/styles/extensions/_menuDropdown.scss
  src/.vuepress/theme/styles/extensions/_sdk-selector.scss
  src/.vuepress/theme/styles/layout/_tabs.scss
  src/.vuepress/theme/styles/layout/_topMenu.scss
  src/.vuepress/theme/styles/main.scss
Labels: changelog:enhancements

#501 [docsearch] using docs index on our app
  src/.vuepress/theme/Search.vue
Labels: changelog:enhancements
