Repository kuzzleio/documentation, pull requests merged in 2020-10, with the labels that each got.

#475 Fix SinceBadge Vue
  src/.vuepress/components/SinceBadge.vue
Labels: changelog:bug-fixes

#476 [CSS] fix tabs width and add paddings
  src/.vuepress/theme/styles/layout/_sdk-tabs.scss
Labels: changelog:enhancements

#477 Add custom table component
  README.md
  src/.vuepress/components/CustomTable.vue
Labels: changelog:new-features

#480 Fix CustomTable icons
  README.md
  src/.vuepress/components/IconTable.vue
Labels: changelog:bug-fixes

#481 Add prev and next links custom component
  README.md
  src/.vuepress/components/GuidesLinks.vue
Labels: changelog:new-features
