Repository kuzzleio/documentation, pull requests merged in 2021-06, with the labels that each got.

#532 Better Open Graph meta tags
  src/.vuepress/config.js
  src/.vuepress/helpers.js
  src/.vuepress/meta-tags-plugin/mixin.js
Labels: changelog:enhancements

#533 [ClosedSourceBanner] Improve English statement
  src/.vuepress/components/ClosedSourcesBanner.vue
Labels: changelog:exclude

#534 Fix open sub-menu height
  src/.vuepress/theme/Sidebar.vue
  src/.vuepress/theme/styles/layout/_base.scss
  src/.vuepress/theme/styles/layout/_content.scss
  src/.vuepress/theme/styles/layout/_sidebar.scss
Labels: changelog:bug-fixes

#535 Better og:image meta tag
  src/.vuepress/config.js
  src/.vuepress/meta-tags-plugin/mixin.js
Labels: changelog:enhancements

#536 Dart v3
  .repos/repositories.yml
  src/.vuepress/sections.json
  src/sdk/dart/3
Labels: changelog:new-features
