Repository kuzzleio/documentation, pull requests merged in 2021-04, with the labels that each got.

#521 Add workflows and device-manager plugins
  .repos/repositories.yml
  src/.vuepress/external-plugins.json
  src/.vuepress/public/logos/device-manager.svg
  src/.vuepress/public/logos/workflows.svg
  src/official-plugins/device-manager/1
  src/official-plugins/workflows/1
Labels: changelog:enhancements

#525 [HOTFIX] Use git for private repos
  .repos/repositories.yml
Labels: changelog:bug-fixes

#526 Revert "[HOTFIX] Use git for private repos"
  .repos/repositories.yml
Labels: changelog:exclude

#524 Add "robot:noindex" meta in the pages of the old versions of Kuzzle
  src/.vuepress/meta-tags-plugin/mixin.js
Labels: changelog:enhancements
